name: deploy to raspi

on:
  workflow_dispatch:
  workflow_run:
    workflows: [build and push docker image]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          password: ${{ secrets.RPI_PASSWORD }}
          port: 22
          proxy_host: ${{ secrets.EC2_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_REPO_PATH }} && git pull
            cp ${{ secrets.SERVER_REPO_PATH }}/projects/vidwiz/.env ${{ secrets.VIDWIZ_REPO_PATH }}/.env
            cd ${{ secrets.VIDWIZ_REPO_PATH }} && git pull
            docker pull adhirajpandey/vidwiz:latest
            docker compose down || true
            docker compose up -d
            sudo systemctl daemon-reload
            sudo systemctl restart vidwiz-transcript-helper.service
            sudo systemctl restart vidwiz-metadata-helper.service
